
on:
  push:
    branches:
    - docker-actions
  # pull_request:
  #   branches:
  #   - master

jobs:

  deployAnsible:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/ansible
      with: 
        playbook: docker-playbook.yml
        inventory: inventory.yml