
on:
  push:
    branches:
    - docker-actions
  # pull_request:
  #   branches:
  #   - master

jobs:


  deployAnsible:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with: 
        playbook: docker-playbook.yml
        inventory: inventory.yml